spring.application.name=country-service

# Standard port for backend to avoid conflict with React (3000/5173)
server.port=8080

# Enable CORS for local frontend
management.endpoints.web.exposure.include=*
